version: '3'
services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80" # HTTP
      - "8080:8080" # Web UI
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"